name: Project/User Story
description: Describe a project or user story (Collection of issues)
labels: ["type:user_story", "triage-required"]
body:
  - type: textarea
    attributes:
      label: Objective of the story
      description: >
        A clear and concise description of what the user should be able to do at the end of this work
    validations:
      required: true
  - type: textarea
    attributes:
      label: Linked Issues
      description: >
        A bulleted list of all linked issues (hopefully sorted in order of execution & dependencies)
      placeholder: >
        E.g.:
        - [ ] #Issue A
        - [ ] #Issue B
    validations:
      required: false
