name: Create release

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
permissions:
  id-token: write
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Bump build number
        run: |
          make bump
          make bump_build_number
      - name: Check for changes created by the formatter
        id: check_changes
        run: |
          git diff --quiet || echo "::set-output name=has_changes::true"
      - name: Commit changes if there are any formatting changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git add -u
          git commit -m "chore: bump patch version and build number"
          git push
